version: '3.9'

services:
  vue-app:
    build:
      context: .
    container_name: vue-app
    restart: always
    volumes:
      - ./src:/app/src
      - /app/src/node_modules
    ports:
      - "8080:8080"
      - "24678:24678"
    command: npm run dev && npm run clear:vite
